# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'test',:path =>'/Users/zhangmin/Desktop/YUU/test.podspec'

end
